### ISSUE TITLE
RATINGS UND VOTINGS WERDEN GELÖSCHT

### ISSUE THREAD

**Issue by whosFritz** [olech2412/EssensGetter-2.0#22]
SOFORT FIXEN SONST ENDE HIER

MEINE FRESSE

**Comment by olech2412** [comment]
Dear Mr. Schubert,

Thank you for opening a ticket with us. I'm sorry to hear that you're having trouble with the ratings and voting of dishes being deleted in the backend. I wanted to let you know that our team has located the issue and is working hard to fix the disruption in the system. It appears that the problem was introduced with the recent feature update.

We appreciate your patience as we work to resolve this issue as quickly as possible. If you have any further questions or concerns, please do not hesitate to reach out.

Best regards,

Mr. Christoph

**Comment by olech2412** [comment]
I wanted to let you know that we have forwarded your ticket to the appropriate department and they will be informed as soon as we have more information. I will now escalate your ticket to ensure it receives the necessary attention and priority.

We understand how important it is to have the ratings and voting of dishes properly functioning in the backend, and we are committed to resolving this issue as soon as possible. Thank you for your understanding and cooperation.

Best regards,

Mr. Christoph

**Comment by olech2412** [comment]
Dear Mr. Schubert,

I wanted to provide you with an update on your ticket. Your complaint has been received by the correct department and is currently being worked on by our technical team. If you would like to see any additional information regarding the status of your issue, you can do so by checking the branch attached to the issue.

We understand the urgency of this matter and our team is doing everything they can to resolve the issue as soon as possible. Thank you for your patience and please let us know if there is anything else we can assist you with.

Best regards,

Mr. Christoph

**Comment by olech2412** [comment]
Dear Mr. Schubert,

I am pleased to inform you that our technical team has successfully located the issue and it has been fixed in the new source code. The software will be patched, most likely on the coming Monday.

We appreciate your patience and understanding during this time, and we apologize for any inconvenience this may have caused. If you have any further concerns, please don't hesitate to reach out.

Best regards,

Mr. Christoph
